app/views/main/routes.py
from flask import Blueprint, session, abort
from .forms import Login_Form, Registration_Form
from app.lib.db_actions import *
from flask_login import login_user, current_user, logout_user, login_required
from app.views.teachers.utils import teacher_required
from flask import render_template, url_for, flash, redirect, request
from app import mail
from flask_mail import Message
import secrets
import folium
from app.lib.models import *

main = Blueprint('main', __name__)


@main.route('/')
def index():
    """Reinderizza alla root del sito"""

    users = User.query.all()
    return render_template('index.html', users=users)


@main.route('/login', methods=['GET', 'POST'])
def login():
    """Reinderizza alla schermata di login"""

    # Controlla se l'utente ha già fatto l'accesso
    if current_user.is_authenticated:
        flash("Accesso già effettuato", 'danger')
        return redirect(url_for('main.index'))

    form = Login_Form()

    # Controlla che il form sia valido
    if form.validate_on_submit():

        user = get_user_by_email(form.email.data)

        if(not user):
            flash("Account non registrato", 'danger')
            return redirect(url_for('main.login'))

        if(not user.is_active):
            flash("Account non attivo: verifica l'account tramite l'email inviata a " +
                  user.email, 'danger')
            return redirect(url_for('main.login'))

        # Crittografia della password
        if bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)

            # Assegnazione del ruolo nella sessione (Studente o Professore)
            if get_student_by_id(user.id_user):
                session['role'] = 'student'
            else:
                session['role'] = 'teacher'
                flash("Accesso come professore", 'success')
                return redirect(url_for('teachers.dashboard'))

            # Reinderizza alla pagina precedentemente richiesta prima di effettuare il login
            next_page = request.args.get('next')

            return redirect(next_page) if next_page else redirect(url_for('students.dashboard'))
        else:
            flash('Accesso negato', 'danger')

    return render_template('login.html', form=form)


def send_verification_email(token, email):
    """Invia una email di verifica per attivare l'account in seguito alla registrazione"""

    msg = Message("Attivazione account PCTO Unive",
                  sender="noreply.pcto@gmail.com",
                  recipients=[email])

    msg.body = "Conferma il tuo account cliccando sul seguente link: http://localhost:5000/verify_account/" + token

    mail.send(msg)


@main.route('/verify_account/<string:token>')
def verify_account(token):
    """Controlla che il token di verifica corrisponda a quello associato all'utente nel database"""

    if(set_user_active(token)):
        flash('Account attivato!', 'success')
    else:
        flash('Account non attivato', 'danger')

    return redirect(url_for('main.login'))


@main.route('/register', methods=['GET', 'POST'])
def register():
    """Reinderizza alla schermata di registrazione"""

    # Controlla se l'utente ha già effettuato l'accesso
    if current_user.is_authenticated:
        flash("Accesso già effettuato", 'danger')
        return redirect(url_for('main.index'))

    form = Registration_Form()

    if form.validate_on_submit():

        # Generazione del toke univoco per l'attivazione dell'account
        token = secrets.token_urlsafe(16)
        insert_token(token, form.email.data)
        insert_user(form)

        send_verification_email(token, form.email.data)

        flash('Email di verifica inviata a ' + form.email.data, 'success')

    return render_template('register.html', form=form)


@main.route('/logout')
def logout():
    """Effettua il logout dalla web application"""

    logout_user()
    session.clear()
    return redirect(url_for('main.index'))

@main.route('/profile')
@login_required
def profile():
    """Reinderizza alla schermata del profilo privato dello studente"""

    return render_template('profile.html')


@main.route('/course_page/<int:id>')
@login_required
def course_page(id):
    """Reinderizza alla schermata di presentazione del corso selezionato"""

    # Controlla che l'utente sia effettivamente iscritto al corso
    if current_user.id_user not in get_users_from_course(id):
        abort(404)

    # Crea mappa nelle coordinate indicate
    # location=[latitude, longitude]
    # zoom_start imposta lo zoom di partenza della mappa

    # seleziona l'edificio in cui si terrà la prossima lezione del corso
    building = get_building_from_lesson(id)
    # seleziona i partecipanti al corso
    partecipants = get_subscribed_students_data(id)

    lessons = get_course_lessons(id)

    if building:
        map = folium.Map(
            location=[building.latitude, building.longitude], zoom_start=18)

        # Crea un marker nelle coordinate indicate e aggiungilo alla mappa
        folium.Marker(
            location = [building.latitude, building.longitude],
            popup = building.b_name
            ).add_to(map)
        
        # _repr_html_() renderizza la mappa e la visualizza
        return render_template('course_page.html', map=map._repr_html_(), course=get_course_by_id(id), lessons=lessons, partecipants=partecipants)

    return render_template('course_page.html', course=get_course_by_id(id), lessons=lessons, partecipants=partecipants)


@login_required
@teacher_required
@main.route('/load_data')
def load_data():
    """Scarica i dati delle sedi e delle aule nel database"""

    import urllib.request
    import json

    # Importazione delle sedi
    with urllib.request.urlopen("http://apps.unive.it/sitows/didattica/sedi") as url:
        data = json.loads(url.read().decode())
        for datas in data:

            if isinstance(datas['COORDINATE'], str):
                coordinates_list = datas['COORDINATE'].split(",")
                coordinate_x = coordinates_list[0]
                coordinate_y = coordinates_list[1]

            newBuilding = Building(
                id_building=datas['SEDE_ID'], b_name=datas['NOME'], longitude=coordinate_x, latitude=coordinate_y)

            db.session.add(newBuilding)
            db.session.commit()
            db.session.flush()

    # Importazione delle aule
    with urllib.request.urlopen("https://apps.unive.it/sitows/didattica/aule") as url:
        data = json.loads(url.read().decode())
        for datas in data:

            if get_building_from_classroom(datas['SEDE_ID']):
                newClassroom = Classroom(
                    id_classroom=datas['AULA_ID'], c_name=datas['NOME'], capacity=datas['POSTI'], id_building=datas['SEDE_ID'])
                db.session.add(newClassroom)
                db.session.flush()

    db.session.commit()
    return 'done'

app/views/student.py
from flask import Blueprint
from flask import render_template, url_for, redirect, flash
from app.lib.db_actions import *
from flask_login import current_user, login_required

from .authentication import authentication_blueprint

student_blueprint = Blueprint('student', __name__)
student_blueprint.register_blueprint(authentication_blueprint)

@student_blueprint.route('/student/dashboard')
@login_required
def student_dashboard():
    if get_student_by_id(current_user.id_user) is None:
        return redirect(url_for('authentication.login'))

    return render_template('student.html', courses=get_all_course(), template='dashboard')


@student_blueprint.route('/student/profile')
@login_required
def student_profile():
    return render_template('profile.html', user_type='student', template='profile')

app/views/students/routes.py
from flask import Blueprint, jsonify, render_template
from app.lib.db_actions import *
from flask_login import current_user, login_required
from .utils import student_required
from app.lib.models_schema import UserSchema, CourseSchema

students = Blueprint('students', __name__)


@students.route('/dashboard')
@login_required
@student_required
def dashboard():
    """Reinderizza alla schermata dashboard dello studente"""

    return render_template('students/student_dashboard.html', courses=get_all_courses())


@students.route('/my_courses')
@login_required
@student_required
def user_courses():
    """Reinderizza alla schermata di visualizzazione dei corsi ai quali lo studente è iscritto"""

    return render_template('students/student_courses.html', courses=get_courses_by_student(current_user.id_user))


# UTILITY per Ajax

@students.route('/subscription/<int:id_course>', methods=['GET', 'POST'])
@login_required
@student_required
def subscription_to_course(id_course):
    """Procedura di iscrizione ad un corso"""

    course = get_course_by_id(id_course)

    # Controlla che lo studente non sia già iscritto al corso selezionato
    if(is_student_already_subscribed(id_student=current_user.id_user, id_course=id_course)):
        response = {'mess': 'Errore: sei già iscritto a <strong>' + course.c_name + '</strong>!', 'type': 'danger'}
    else:
        insert_course_subscription(id_student=current_user.id_user, id_course=id_course)
        response = {'mess': 'Iscritto correttamente a <strong>' + course.c_name + '</strong>!', 'type': 'success'}
    return jsonify(response)


@students.route('/delete_subscription/<int:id_course>', methods=['GET', 'POST'])
@login_required
@student_required
def delete_subscription_to_course(id_course):
    """Procedura di disiscrizione ad un corso"""

    delete_course_subscription(id_student=current_user.id_user, id_course=id_course)
    response = {'mess': 'Iscrizione cancellata correttamente!',
                'type': 'success',
                'n_corsi': len(get_courses_by_student(current_user.id_user))}

    return jsonify(response)


@students.route('/is_subscribed/<int:id_course>', methods=['GET', 'POST'])
@login_required
@student_required
def is_subscribed(id_course):
    """Controlla se lo studente è già iscritto ad un corso"""

    response = db.session.query(StudentsCourses).filter(StudentsCourses.id_course == id_course, StudentsCourses.id_student == current_user.id_user).first()
    if(response):
        return 'ok'
    else:
        return ''


@students.route('/description/<int:id_course>', methods=['GET', 'POST'])
@login_required
@student_required
def description(id_course):
    """Seleziona i dettagli di un determinato corso"""

    user_schema = UserSchema()
    course_schema = CourseSchema()

    prof = get_course_professor(id_course)
    courses = get_all_courses()
    course = get_course_by_id(id_course)

    response = {'subscription_number': len(get_subscribed_students(id_course)),
                'prof': user_schema.dump(prof),
                'courses': course_schema.dump(courses),
                'course': course_schema.dump(course),
                'is_already_subscribed': is_student_already_subscribed(current_user.id_user, id_course)}

    return jsonify(response)

app/templates/students/dashboard.html
{% extends 'layout.html' %}

{% block title %}Dashboard - UniVE PCTO{% endblock %}

{% block content %}

<h2>Corsi disponibili</h2><br>

{% for category, sublist in courses %}
    {% if sublist %}     
        <div class="accordion" id="accordionCourses">
            <div class="accordion-item mb-3">
                <h2 class="accordion-header" id="heading{{category.id_category}}">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{category.id_category}}" aria-expanded="false" aria-controls="collapse{{category.id_category}}">
                        <strong>{{category.c_name}}</strong>
                    </button>
                </h2>
                <div id="collapse{{category.id_category}}" class="accordion-collapse collapse" aria-labelledby="heading{{category.id_category}}" data-bs-parent="#accordionExample">
                    <div class="accordion-body container-fluid table-responsive">                  
                        <table class="table table-hover">
                            <thead>
                                <tr class="d-flex"> 
                                    <th class="col-2">Titolo</th>
                                    <th class="col-3">Descrizione</th>
                                    <th class="col-2">Creatore</th>
                                    <th class="col-2">Data Creazione</th>
                                    <th class="col-1">N. posti</th>
                                    <th class="col-2">Disponibilità</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for course in sublist %}
                                <tr class="d-flex">
                                    <th class="col-2">{{course.Course.c_name}}</th>
                                    <td class="col-3 line-clamp pb-1">{{course.Course.description}}</td>
                                    <td class="col-2">{{course.User.first_name}} {{course.User.last_name}}</td>
                                    <td class="col-2">{{course.Course.creation_date}}</td>
                                    <td class="col-1">{{course.Course.max_partecipants}}</td>
                                    <td class="col-2" id="detailButton_{{course.Course.id_course}}">
                                        <script>
                                            function subscribed(){
                                                $.ajax({
                                                    type: "POST",
                                                    dataType: 'text',
                                                    url: "/student/is_subscribed/{{course.Course.id_course}}",
                                                }).done((response) => {
                                                    if(response == 'ok'){
                                                        $('#detailButton_{{course.Course.id_course}}').html(`
                                                        <div class="d-grid gap-2">
                                                            <button type="button" class="btn btn-success" data-bs-toggle="modal" onclick="info('{{course.Course.id_course}}')">
                                                                Iscritto
                                                                <i class="fa-solid fa-user-check"></i>
                                                            </button>
                                                        </div>
                                                        `)
                                                    }else{
                                                        $('#detailButton_{{course.Course.id_course}}').html(`
                                                            <div class="d-grid gap-2">
                                                                <button type="button" class="btn btn-info" data-bs-toggle="modal" onclick="info('{{course.Course.id_course}}')">
                                                                    Dettagli
                                                                </button>
                                                            </div>
                                                        `)
                                                    }
                                                });
                                            }
        
                                            window.onpaint = subscribed();
                                        </script>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endfor %}
<!-- MODALS -->
<div class="modal fade" id="modalPlaceholder" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle"><!-- title -->></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modalBody">
                <!-- modal body here -->
            </div>
            <div class="modal-footer" id="modalFooter">
                <!-- modal footer here -->
            </div>
        </div>
    </div>
</div>

<script>
    function info(id){
        $.ajax({
            type: "POST",
            url: "/student/description/"+id,
        }).done((response) => {
            let button = `<button type ="button" class="btn btn-success" onclick="subscribe(${id})">Iscriviti</button>`
            if(response.is_already_subscribed){
                button = ``
            }
            if(parseInt(response.subscription_number) >= response.course.max_partecipants){
                button = `<button type ="button" class="btn btn-danger" disabled>Iscrizioni al completo</button>`
            }
            
            let percentage = parseInt(response.subscription_number) / response.course.max_partecipants * 100

            $('#modalTitle').html(`
                <strong>${response.course.c_name}</strong>
            `)

            $('#modalBody').html(`
                <div class="row">
                    <h7><strong>Descrizione:</strong> ${response.course.description}</h7>
                </div>
                <div class="row">
                    <h7><strong>Professore:</strong> ${response.prof.first_name} ${response.prof.last_name}</h7>
                </div>
                <div class="row">
                    <h7><strong>Email:</strong> ${response.prof.email}</h7>
                </div>
                <div class="mt-2">
                    <div class="progress">
                        <div class="progress-bar" role="progressbar" style="width: ${percentage}%" aria-valuenow="${percentage}" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    <div class="mt-1"> <span class="text1">${response.subscription_number} iscritti <span class="text2">su ${response.course.max_partecipants} disponibili</span></span> </div>
                </div>
            `)

            $('#modalFooter').html(`
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Chiudi</button>
                ${button}
            `)

            $("#modalPlaceholder").modal("show");
        });
    }

    function subscribe(id){
        $.ajax({
            type: "POST",
            url: "/student/subscription/"+id,
        }).done((response) => {

            $('#alertPlaceholder').append(`
                <div class="alert alert-${response.type} alert-dismissible" id="sub-${id}" role="alert">
                    <div>${response.mess}</div>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            `)

            $("#modalPlaceholder").modal("hide");

            $(`#detailButton_${id}`).html(`
            <div class="d-grid gap-2">
                <button type="button" class="btn btn-success" data-bs-toggle="modal" onclick="info(${id})">
                    Iscritto
                    <i class="fa-solid fa-user-check"></i>
                </button>
            </div>
        `)
            
            $(`#sub-${id}`).fadeTo(2000, 500).slideUp(500, function(){
                $(`#sub-${id}`).alert('close');
            });
        });
    }
</script>

<style>
    .line-clamp {
        overflow: hidden;
        text-overflow: ellipsis;
        display: -webkit-box;
        -webkit-line-clamp: 5; /* number of lines to show */
        -webkit-box-orient: vertical;
      }
</style>

{% endblock content %}

app/templates/students/student_courses.html
{% extends 'layout.html' %}

{% block title %}I miei corsi - UniVE PCTO{% endblock %}

{% block content %}

    <h1>Corsi di {{ current_user.first_name }}</h1>

    <p id="noCourse">
    {% if not courses %}
        Sembra che tu non sia iscritto a nessun corso... <br>
        Clicca  <a href="{{ url_for('students.dashboard') }}">qui</a> per vedere tutti i corsi disponibili
    {% endif %}
    </p>

    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for course in courses %}
            <div class="col" id="course-{{course.id_course}}">
                <div class="card">
                    <h5 class="card-header">{{course.c_name}}</h5>
                    <div class="card-body">
                        <p class="card-text line-clamp pb-1">{{course.description}}</p>
                        <p class="card-text">{{course.creation_date}}</p>
                        <a href="{{ url_for('main.course_page',id = course.id_course) }}"><button class="btn btn-info">Info <i class="fa-solid fa-circle-info"></i></button></a>
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" onclick="info('{{course.id_course}}')">
                            Cancella iscrizione
                        </button>
                    </div>
                </div>
            </div>

        {% endfor %}

    </div>

    <div class="modal fade" id="modalPlaceholder" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle"><!-- title -->></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-footer" id="modalFooter">
                <!-- modal footer here -->
            </div>
        </div>
    </div>
    </div>

    <script>
        function info(id){
            $('#modalTitle').html(`
                <strong>Cancellare iscrizione?</strong>
            `)

            $('#modalFooter').html(`
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annulla</button>
                <button type ="button" class="btn btn-danger" onclick="delete_subscription('${id}')">Cancella iscrizione</button>
            `)

            $("#modalPlaceholder").modal("show");
        }

        function delete_subscription(id){
            $.ajax({
                type: "POST",
                url: "/student/delete_subscription/"+id,
            }).done((response) => {
                $('#alertPlaceholder').append(`
                <div class="alert alert-${response.type} alert-dismissible" id="sub-${id}" role="alert">
                    <div>${response.mess}</div>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                `)
                $(`#course-${id}`).remove()

                console.log(response.n_corsi)

                if(response.n_corsi == 0){
                    $("#noCourse").html(
                    `
                    Sembra che tu non sia iscritto a nessun corso... <br>
                    Clicca  <a href="{{ url_for('students.dashboard') }}">qui</a> per vedere tutti i corsi disponibili
                    `
                    );
                }

                $("#modalPlaceholder").modal("hide");

                $(`#sub-${id}`).fadeTo(2000, 500).slideUp(500, function(){
                    $(`#sub-${id}`).alert('close');
                });
            });
        }
    </script>

<style>
    .line-clamp {
        overflow: hidden;
        text-overflow: ellipsis;
        display: -webkit-box;
        -webkit-line-clamp: 3; /* number of lines to show */
        -webkit-box-orient: vertical;
      }
</style>

{% endblock content %}

app/templates/students/user_courses.html
{% extends 'layout.html' %}

{% block title %}I miei corsi - UniVE PCTO{% endblock %}

{% block content %}

    <h1>Corsi di {{ current_user.first_name }}</h1>

    <p id="noCourse">
    {% if not courses %}
        Sembra che tu non sia iscritto a nessun corso... <br>
        Clicca  <a href="{{ url_for('students.dashboard') }}">qui</a> per vedere tutti i corsi disponibili
    {% endif %}
    </p>

    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for course in courses %}
            <div class="col" id="course-{{course.id_course}}">
                <div class="card">
                    <h5 class="card-header">{{course.c_name}}</h5>
                    <div class="card-body">
                        <p class="card-text">{{course.description}}</p>
                        <p class="card-text">{{course.creation_date}}</p>
                        <a href="{{ url_for('main.course_page',id = course.id_course) }}"><button class="btn btn-info">Info <i class="fa-solid fa-circle-info"></i></button></a>
                        <button type="button" class="btn btn-danger" data-bs-toggle="modal" onclick="info('{{course.id_course}}')">
                            Cancella iscrizione
                        </button>
                    </div>
                </div>
            </div>

        {% endfor %}

    </div>

    <div class="modal fade" id="modalPlaceholder" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle"><!-- title -->></h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-footer" id="modalFooter">
                <!-- modal footer here -->
            </div>
        </div>
    </div>
    </div>

    <script>
        function info(id){
            $('#modalTitle').html(`
                <strong>Cancellare iscrizione?</strong>
            `)

            $('#modalFooter').html(`
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Annulla</button>
                <button type ="button" class="btn btn-danger" onclick="delete_subscription('${id}')">Cancella iscrizione</button>
            `)

            $("#modalPlaceholder").modal("show");
        }

        function delete_subscription(id){
            $.ajax({
                type: "POST",
                url: "/student/delete_subscription/"+id,
            }).done((response) => {
                $('#alertPlaceholder').append(`
                <div class="alert alert-${response.type} alert-dismissible" id="sub-${id}" role="alert">
                    <div>${response.mess}</div>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                `)
                $(`#course-${id}`).remove()

                console.log(response.n_corsi)

                if(response.n_corsi == 0){
                    $("#noCourse").html(
                    `
                    Sembra che tu non sia iscritto a nessun corso... <br>
                    Clicca  <a href="{{ url_for('students.dashboard') }}">qui</a> per vedere tutti i corsi disponibili
                    `
                    );
                }

                $("#modalPlaceholder").modal("hide");

                $(`#sub-${id}`).fadeTo(2000, 500).slideUp(500, function(){
                    $(`#sub-${id}`).alert('close');
                });
            });
        }
    </script>

{% endblock content %}