app/views/teachers/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, IntegerField, SelectField, DateField
from wtforms.validators import DataRequired
class NewCourse_Form(FlaskForm):
    """Form di creazione nuovo corso"""

    name             = StringField('Nome del corso', validators=[DataRequired()])
    description      = TextAreaField('Descrizione')
    max_partecipants = IntegerField('Massimo numero di partecipanti')
    min_partecipants = IntegerField('Minimo numero di partecipanti')
    min_lessons      = IntegerField('Minimo numero di lezioni')
    duration         = IntegerField('Durata delle lezioni')
    category         = SelectField('Categoria', choices=[]) # Le categorie verranno aggiornate dinamicamente
    submit           = SubmitField('Conferma')


class NewLesson_Form(FlaskForm):
    """Form di creazione delle lezioni"""
    
    building         = SelectField('Edificio', choices=[])
    classroom        = SelectField('Aula', choices=[])
    mode             = SelectField('Modalità', choices=['Presenza','Online','Duale'])
    description      = TextAreaField('Descrizione')
    date             = DateField('Data')
    time             = SelectField('Orario', coerce = int, choices=[(0,'08:45'), (1,'10:30'), (2,'12:15'), (3,"14:00"), (4,"15:45"), (5,"17:30")])
    submit           = SubmitField('Conferma')

app/views/teacher.py
from flask import Blueprint
from flask import render_template, url_for, redirect
from app.lib.db_actions import *
from app.lib.forms import newCourseForm
from flask_login import current_user, login_required

from .authentication import authentication_blueprint

teacher_blueprint = Blueprint('teacher', __name__)
teacher_blueprint.register_blueprint(authentication_blueprint)

@teacher_blueprint.route('/teacher/dashboard', methods=['GET', 'POST'])
@login_required
def teacher_dashboard():
    if get_student_by_id(current_user.id_user):
        return redirect(url_for('authentication.login'))

    form = newCourseForm()
    form.category.choices = [(category.id_category, category.c_name) for category in get_all_categories()]

    if form.validate_on_submit():
        insert_course(form)
        return redirect(url_for('teacher'))

    return render_template('teacher.html', courses=get_all_courses_from_teacher(current_user.id_user), form=form)


@teacher_blueprint.route('/teacher/profile')
@login_required
def teacher_profile():
    return render_template('profile.html', user_type='teacher', template='profile')

app/views/teachers/routes.py
import json
from flask import Blueprint, request, jsonify, abort, render_template, url_for, redirect, flash
from app.lib.models import Building
from app.lib.models_schema import ClassroomSchema
from .forms import NewCourse_Form, NewLesson_Form
from app.lib.db_actions import *
from flask_login import current_user, login_required
from .utils import teacher_required
import simplejson as json
teachers = Blueprint('teachers', __name__)

@teachers.route('/dashboard')
@login_required
@teacher_required
def dashboard():
    """Reinderizza alla schermata dashboard del professore"""

    return render_template('teachers/teacher_dashboard.html', courses=get_all_courses_from_teacher(current_user.id_user))


@teachers.route('/new_course', methods=['GET', 'POST'])
@login_required
@teacher_required
def newCourse():
    """Reinderizza al form di creazione di un nuovo corso"""

    form = NewCourse_Form()
    form.category.choices = [(category.id_category, category.c_name) for category in get_all_categories()]

    #Validazione del form e inserimento del corso nel database
    if form.validate_on_submit():
        insert_course(form)
        return redirect(url_for('teachers.dashboard'))
    return render_template('teachers/create_course.html', form=form)


@teachers.route('/edit_course/<int:id_course>', methods=['GET', 'POST'])
@login_required
@teacher_required
def edit_course(id_course):
    """Reinderizza alla schermata di modifica del corso selezionato"""

    data_string = request.form.get('a')
    data = {}

    if data_string:
        data = json.loads(data_string)
        update_course(id_course, data)

    categories_left = get_all_categories()
    category = get_course_category(id_course)
    categories_left.remove(category)

    return render_template('teachers/edit_course.html', course=get_course_by_id(id_course), categories=categories_left, this_category=category)


@teachers.route('<int:id_course>/new_lesson', methods=['GET', 'POST'])
@login_required
@teacher_required
def newLesson(id_course):
    """Reinderizza alla schermata di creazione di una nuova lezione"""

    if current_user.id_user is not get_course_owner(id_course):
        abort(404)
        
    new_lesson = NewLesson_Form()
    
    new_lesson.building.choices = [(building.id_building, building.b_name) for building in Building.query.all()]
 
    if request.method == 'POST':
        new_lesson.classroom.choices = [(classroom.id_classroom, classroom.c_name) for classroom in Classroom.query.filter(Classroom.id_building == request.form.get('building')).all()]
    else:
        new_lesson.classroom.choices = [(classroom.id_classroom, classroom.c_name) for classroom in Classroom.query.filter(Classroom.id_building == new_lesson.building.choices[0][0]).all()]

    #Validazione del form e controllo di una eventuale sovrapposizione con altre lezioni
    if new_lesson.validate_on_submit():
        if not check_lesson_availability(new_lesson):
            flash('L\' aula inserita è già prenotata', 'danger')
            return render_template('teachers/new_lesson.html', id_course=id_course, form=new_lesson)

        insert_lesson(new_lesson, id_course)
        # Lezione inserita
        return redirect(url_for('main.course_page', id=id_course))

    return render_template('teachers/new_lesson.html', id_course=id_course, form=new_lesson)


@teachers.route('/<int:id_course>/lessons', methods = ['GET','POST'])
@login_required
@teacher_required
def lessons(id_course):
    """Reinderizza alla schermata di visualizzazione delle lezioni del corso selezionato"""

    lessons = get_course_lessons(id_course)

    return render_template('teachers/lesson_list.html', course = get_course_by_id(id_course), lessons = lessons)



# UTILITY per Ajax

@teachers.route('/getClassrooms/<string:id_building>', methods=['GET', 'POST'])
@login_required
@teacher_required
def getClassrooms(id_building):
    """Seleziona tutte le aule di una sede (utilizzata nella richiesta AJAX)"""

    class_schema = ClassroomSchema(many=True)
    classrooms = get_classrooms_from_building(id_building)
    return jsonify(class_schema.dump(classrooms))

app/templates/teachers/course_description.html
{% extends 'layout.html' %}

{% block title %}Descrizione corso - UniVE PCTO{% endblock %}

{% block content %}
    <script src="{{url_for('static', filename='course_description.js')}}"></script>

    <H3>Descrizione corso:</H3>
    
    <div class="mb-3">
        <h5>Nome corso:</h5>
        <input type="text" class="form-control" id="tittle" value = "{{course.c_name}}" disabled>
    </div>

    <div class="mb-3">
        <h5>Descrizione:</h5>
        <textarea class="form-control" id="description"  style ="resize:none; height: 100px" disabled>{{course.description}}</textarea>
    </div>

    <div class ="mb-3">
        <h5>Min iscritti:</h5>
        <input class="form-control" id="min_subscribers" name="min_subscribers" type="number" value="{{course.min_partecipants}}" disabled>
    </div>

    <div class ="mb-3">
        <h5>Max iscritti:</h5>
        <input class="form-control" id="max_subscribers" name="max_subscribers" type="number" value="{{course.max_partecipants}}" disabled>
    </div>

    <div class ="mb-3">
        <h5>Durata lezioni:</h5>
        <input class="form-control" id="lesson_duration" name="lesson_duration" type="number" value="{{course.duration}}" disabled>
    </div>

    <div class ="mb-3">
        <h5>Categoria:</h5>
        <select class="form-select" id = "category" aria-label="Default select example" disabled>
            <option selected>{{this_category.c_name}}</option>
            {% for category in categories %}
                <option value = '{{category.c_name}}'>{{category.c_name}}</option>
            {% endfor %}
          </select>
    </div>

    <div class = "mb-3">
        <p id="buttonRow">
            <button class="btn btn-primary" onclick="updateCourse('{{course.id_course}}')" id = "updateButton">Aggiorna</button>
        </p>
    </div>

{% endblock content%}

app/templates/teachers/create_course.html
{% extends 'layout.html' %}

{% block title %}Nuovo corso - UniVE PCTO{% endblock %}

{% block content %}

    <h2>Nuovo corso</h2>

    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}

        <div class="mb-3">
            {{ form.name.label(class="form-label") }}
            {% if form.name.errors %}
                    {{form.name(class="form-control is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
            {% else %}
                {{ form.name(class="form-control") }}
            {% endif %}
        </div>

        <div class="mb-3">
            {{ form.description.label(class="form-label") }}
            {{ form.description(class="form-control") }}
        </div>

        <div class="mb-3">
            {{ form.max_partecipants.label(class="form-label") }}
            {{ form.max_partecipants(class="form-control") }}
        </div>

        <div class="mb-3">
            {{ form.min_partecipants.label(class="form-label") }}
            {{ form.min_partecipants(class="form-control") }}
        </div>

        <div class="mb-3">
            {{ form.min_lessons.label(class="form-label") }}
            {{ form.min_lessons(class="form-control") }}
        </div>

        <div class="mb-3">
            {{ form.duration.label(class="form-label") }}
            {{ form.duration(class="form-control") }}
        </div>

        <div class="mb-3">
            {{ form.category.label(class="form-label") }}
            {{ form.category(class="form-control") }}
        </div>
        
        <div class="mb-3">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
    <a href="{{ url_for('teachers.dashboard') }}"><button class="btn btn-danger">Indietro</button></a>

{% endblock content %}

app/templates/teachers/dashboard.html
{% extends 'layout.html' %}

{% block title %}Dashboard - UniVE PCTO{% endblock %}

{% block content %}
    <h1>Corsi creati</h1>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Titolo</th>
                <th scope="col">Categoria</th>
                <th scope="col">Data Creazione</th>
                <th scope="col">Numero di iscrizioni</th>
                <th scope="col">Azioni</th>
            </tr>
        </thead>
        <tbody>

            {% for course in courses %}
            <tr>
                <th scope="row" ><a href="{{ url_for('main.course_page',id = course.Course.id_course) }}" style="text-decoration: none;">{{course.Course.c_name}}</a></th>
                <td scope="row">{{course.Category.c_name}}</td>
                <td scope="row">{{course.Course.creation_date}}</td>
                <td scope="row">{{course.Course.max_partecipants}}</td>

                <td scope="row">
                    <a href="{{ url_for('main.course_page',id = course.Course.id_course) }}"><button class="btn btn-info">Info <i class="fa-solid fa-circle-info"></i></button></a>
                    <a href="{{ url_for('teachers.edit_course',id_course = course.Course.id_course) }}"><button class="btn btn-warning"><i class="fa-solid fa-pen"></i></button></a>
                </td>

            </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{{ url_for('teachers.newCourse') }}"><button class="btn btn-primary">Crea nuovo corso</button></a>

{% endblock content %}

app/templates/teachers/edit_course.html
{% extends 'layout.html' %}

{% block title %}Descrizione corso - UniVE PCTO{% endblock %}

{% block content %}
    <script src="{{url_for('static', filename='course_description.js')}}"></script>

    <H3>Descrizione corso:</H3>
    
    <div class="mb-3">
        <h5>Nome corso:</h5>
        <input type="text" class="form-control" id="tittle" value = "{{course.c_name}}" disabled>
    </div>

    <div class="mb-3">
        <h5>Descrizione:</h5>
        <textarea class="form-control" id="description"  style ="resize:none; height: 100px" disabled>{{course.description}}</textarea>
    </div>

    <div class ="mb-3">
        <h5>Min iscritti:</h5>
        <input class="form-control" id="min_subscribers" name="min_subscribers" type="number" value="{{course.min_partecipants}}" disabled>
    </div>

    <div class ="mb-3">
        <h5>Max iscritti:</h5>
        <input class="form-control" id="max_subscribers" name="max_subscribers" type="number" value="{{course.max_partecipants}}" disabled>
    </div>

    <div class ="mb-3">
        <h5>Durata lezioni:</h5>
        <input class="form-control" id="lesson_duration" name="lesson_duration" type="number" value="{{course.duration}}" disabled>
    </div>

    <div class ="mb-3">
        <h5>Categoria:</h5>
        <select class="form-select" id = "category" aria-label="Default select example" disabled>
            <option selected>{{this_category.c_name}}</option>
            {% for category in categories %}
                <option value = '{{category.c_name}}'>{{category.c_name}}</option>
            {% endfor %}
          </select>
    </div>

    <div class = "mb-3">
        <p id="buttonRow">
            <button class="btn btn-primary" onclick="updateCourse('{{course.id_course}}')" id = "updateButton">Aggiorna</button>
        </p>
    </div>

{% endblock content%}

app/templates/teachers/new_lesson.html
{% extends 'layout.html' %}

{% block title %}Nuova lezione - UniVE PCTO{% endblock %}

{% block content %}
    <h3>Crea lezione:</h3>

    <div class ='mb-3' id = "single-form">
        <form action="{{url_for('teachers.newLesson', id_course = id_course)}}" method="post" novalidate>

            {{ form.hidden_tag() }}

            <div class="mb-3">
                {{ form.description.label(class="form-label") }}
                {% if form.description.errors %}
                    {{form.description(class="form-control is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.description.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.description(class="form-control") }}
                {% endif %}
            </div>

            <div class="mb-3">
                <div class="row">
                    <div class="col-sm-3">
                        {{ form.date.label(class="form-label") }}
                        {% if form.date.errors %}
                            {{form.date(class="form-control is-invalid")}}
                                <div class="invalid-feedback">
                                    {% for error in form.date.errors %}
                                        <span>{{error}}</span>
                                    {% endfor %}
                                </div>
                        {% else %}
                            {{ form.date(class="form-control") }}
                        {% endif %}
                    </div>
                    <div class="col-sm-1">
                        {{ form.time.label(class="form-label") }}
                        {% if form.time.errors %}
                            {{form.time(class="form-control is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.time.errors %}
                                    <span>{{error}}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.time(class="form-control") }}
                        {% endif %}
                    </div>
                </div>
            </div>

            <div class="mb-3">
                {{ form.mode.label(class="form-label") }}
                {% if form.mode.errors %}
                    {{form.mode(class="form-control is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.mode.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.mode(class="form-control") }}
                {% endif %}
            </div>

            <div class="mb-3">
                {{ form.building.label(class="form-label") }}
                {% if form.building.errors %}
                    {{form.building(class="form-control is-invalid", id="select_building")}}
                    <div class="invalid-feedback">
                        {% for error in form.building.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.building(class="form-control", id="select_building") }}
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.classroom.label(class="form-label") }}
                {% if form.classroom.errors %}
                    {{form.classroom(class="form-control is-invalid", id="select_classroom")}}
                    <div class="invalid-feedback">
                        {% for error in form.classroom.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.classroom(class="form-control", id="select_classroom") }}
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>
    </div>

    <script>

        $('#select_building').change(() => {
            $.ajax({
                type: "POST",
                url: "/teacher/getClassrooms/"+$("#select_building").val(),
            }).done((response) => {
                $('#select_classroom').html(``)
                for(c in response){
                    $('#select_classroom').append(`
                        <option value="${response[c].id_classroom}">${response[c].c_name}</option>
                    `)
                }
            })
        })
    </script>

{% endblock content %}

app/templates/teachers/teacher.html
{% extends 'layout.html' %}
{% block content %}
    <h1>Professore</h1>
    <b>Lista corsi creati</b>
    <ul class="list-group mb-3">
        {% for course in courses %}
            <li class="list-group-item">{{course.c_name}}</li>
        {% endfor %}
    </ul>

    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}

        <div class="mb-3">
            {{ form.name.label(class="form-label") }}
            {% if form.name.errors %}
                    {{form.name(class="form-control is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.name.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
            {% else %}
                {{ form.name(class="form-control") }}
            {% endif %}
        </div>

        <div class="mb-3">
            {{ form.description.label(class="form-label") }}
            {{ form.description(class="form-control") }}
        </div>

        <div class="mb-3">
            {{ form.max_partecipants.label(class="form-label") }}
            {{ form.max_partecipants(class="form-control") }}
        </div>

        <div class="mb-3">
            {{ form.min_partecipants.label(class="form-label") }}
            {{ form.min_partecipants(class="form-control") }}
        </div>

        <div class="mb-3">
            {{ form.min_lessons.label(class="form-label") }}
            {{ form.min_lessons(class="form-control") }}
        </div>

        <div class="mb-3">
            {{ form.duration.label(class="form-label") }}
            {{ form.duration(class="form-control") }}
        </div>

        <div class="mb-3">
            {{ form.category.label(class="form-label") }}
            {{ form.category(class="form-control") }}
        </div>
        
        <div class="mb-3">
            {{ form.submit(class="btn btn-primary") }}
        </div>
      </form>


{% endblock content %}

app/templates/teachers/teacher_dashboard.html
{% extends 'layout.html' %}

{% block title %}Dashboard - UniVE PCTO{% endblock %}

{% block content %}
    <h1>Corsi creati</h1>

    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Titolo</th>
                <th scope="col">Categoria</th>
                <th scope="col">Data Creazione</th>
                <th scope="col">Numero di iscrizioni</th>
                <th scope="col">Azioni</th>
            </tr>
        </thead>
        <tbody>

            {% for course in courses %}
            <tr>
                <th scope="row" ><a href="{{ url_for('main.course_page',id = course.Course.id_course) }}" style="text-decoration: none;">{{course.Course.c_name}}</a></th>
                <td scope="row">{{course.Category.c_name}}</td>
                <td scope="row">{{course.Course.creation_date}}</td>
                <td scope="row">{{course.Course.max_partecipants}}</td>

                <td scope="row">
                    <a href="{{ url_for('main.course_page',id = course.Course.id_course) }}"><button class="btn btn-info">Info <i class="fa-solid fa-circle-info"></i></button></a>
                    <a href="{{ url_for('teachers.edit_course',id_course = course.Course.id_course) }}"><button class="btn btn-warning"><i class="fa-solid fa-pen"></i></button></a>
                </td>

            </tr>
            {% endfor %}
        </tbody>
    </table>

    <a href="{{ url_for('teachers.newCourse') }}"><button class="btn btn-primary">Crea nuovo corso</button></a>

{% endblock content %}