app/views/main/routes.py
from flask import Blueprint, session, abort
from .forms import Login_Form, Registration_Form
from app.lib.db_actions import *
from flask_login import login_user, current_user, logout_user, login_required
from app.views.teachers.utils import teacher_required
from flask import render_template, url_for, flash, redirect, request
from app import mail
from flask_mail import Message
import secrets
import folium
from app.lib.models import *

main = Blueprint('main', __name__)


@main.route('/')
def index():
    """Reinderizza alla root del sito"""

    users = User.query.all()
    return render_template('index.html', users=users)


@main.route('/login', methods=['GET', 'POST'])
def login():
    """Reinderizza alla schermata di login"""

    # Controlla se l'utente ha già fatto l'accesso
    if current_user.is_authenticated:
        flash("Accesso già effettuato", 'danger')
        return redirect(url_for('main.index'))

    form = Login_Form()

    # Controlla che il form sia valido
    if form.validate_on_submit():

        user = get_user_by_email(form.email.data)

        if(not user):
            flash("Account non registrato", 'danger')
            return redirect(url_for('main.login'))

        if(not user.is_active):
            flash("Account non attivo: verifica l'account tramite l'email inviata a " +
                  user.email, 'danger')
            return redirect(url_for('main.login'))

        # Crittografia della password
        if bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)

            # Assegnazione del ruolo nella sessione (Studente o Professore)
            if get_student_by_id(user.id_user):
                session['role'] = 'student'
            else:
                session['role'] = 'teacher'
                flash("Accesso come professore", 'success')
                return redirect(url_for('teachers.dashboard'))

            # Reinderizza alla pagina precedentemente richiesta prima di effettuare il login
            next_page = request.args.get('next')

            return redirect(next_page) if next_page else redirect(url_for('students.dashboard'))
        else:
            flash('Accesso negato', 'danger')

    return render_template('login.html', form=form)


def send_verification_email(token, email):
    """Invia una email di verifica per attivare l'account in seguito alla registrazione"""

    msg = Message("Attivazione account PCTO Unive",
                  sender="noreply.pcto@gmail.com",
                  recipients=[email])

    msg.body = "Conferma il tuo account cliccando sul seguente link: http://localhost:5000/verify_account/" + token

    mail.send(msg)


@main.route('/verify_account/<string:token>')
def verify_account(token):
    """Controlla che il token di verifica corrisponda a quello associato all'utente nel database"""

    if(set_user_active(token)):
        flash('Account attivato!', 'success')
    else:
        flash('Account non attivato', 'danger')

    return redirect(url_for('main.login'))


@main.route('/register', methods=['GET', 'POST'])
def register():
    """Reinderizza alla schermata di registrazione"""

    # Controlla se l'utente ha già effettuato l'accesso
    if current_user.is_authenticated:
        flash("Accesso già effettuato", 'danger')
        return redirect(url_for('main.index'))

    form = Registration_Form()

    if form.validate_on_submit():

        # Generazione del toke univoco per l'attivazione dell'account
        token = secrets.token_urlsafe(16)
        insert_token(token, form.email.data)
        insert_user(form)

        send_verification_email(token, form.email.data)

        flash('Email di verifica inviata a ' + form.email.data, 'success')

    return render_template('register.html', form=form)


@main.route('/logout')
def logout():
    """Effettua il logout dalla web application"""

    logout_user()
    session.clear()
    return redirect(url_for('main.index'))

@main.route('/profile')
@login_required
def profile():
    """Reinderizza alla schermata del profilo privato dello studente"""

    return render_template('profile.html')


@main.route('/course_page/<int:id>')
@login_required
def course_page(id):
    """Reinderizza alla schermata di presentazione del corso selezionato"""

    # Controlla che l'utente sia effettivamente iscritto al corso
    if current_user.id_user not in get_users_from_course(id):
        abort(404)

    # Crea mappa nelle coordinate indicate
    # location=[latitude, longitude]
    # zoom_start imposta lo zoom di partenza della mappa

    # seleziona l'edificio in cui si terrà la prossima lezione del corso
    building = get_building_from_lesson(id)
    # seleziona i partecipanti al corso
    partecipants = get_subscribed_students_data(id)

    lessons = get_course_lessons(id)

    if building:
        map = folium.Map(
            location=[building.latitude, building.longitude], zoom_start=18)

        # Crea un marker nelle coordinate indicate e aggiungilo alla mappa
        folium.Marker(
            location = [building.latitude, building.longitude],
            popup = building.b_name
            ).add_to(map)
        
        # _repr_html_() renderizza la mappa e la visualizza
        return render_template('course_page.html', map=map._repr_html_(), course=get_course_by_id(id), lessons=lessons, partecipants=partecipants)

    return render_template('course_page.html', course=get_course_by_id(id), lessons=lessons, partecipants=partecipants)


@login_required
@teacher_required
@main.route('/load_data')
def load_data():
    """Scarica i dati delle sedi e delle aule nel database"""

    import urllib.request
    import json

    # Importazione delle sedi
    with urllib.request.urlopen("http://apps.unive.it/sitows/didattica/sedi") as url:
        data = json.loads(url.read().decode())
        for datas in data:

            if isinstance(datas['COORDINATE'], str):
                coordinates_list = datas['COORDINATE'].split(",")
                coordinate_x = coordinates_list[0]
                coordinate_y = coordinates_list[1]

            newBuilding = Building(
                id_building=datas['SEDE_ID'], b_name=datas['NOME'], longitude=coordinate_x, latitude=coordinate_y)

            db.session.add(newBuilding)
            db.session.commit()
            db.session.flush()

    # Importazione delle aule
    with urllib.request.urlopen("https://apps.unive.it/sitows/didattica/aule") as url:
        data = json.loads(url.read().decode())
        for datas in data:

            if get_building_from_classroom(datas['SEDE_ID']):
                newClassroom = Classroom(
                    id_classroom=datas['AULA_ID'], c_name=datas['NOME'], capacity=datas['POSTI'], id_building=datas['SEDE_ID'])
                db.session.add(newClassroom)
                db.session.flush()

    db.session.commit()
    return 'done'

app/views/teachers/routes.py
import json
from flask import Blueprint, request, jsonify, abort, render_template, url_for, redirect, flash
from app.lib.models import Building
from app.lib.models_schema import ClassroomSchema
from .forms import NewCourse_Form, NewLesson_Form
from app.lib.db_actions import *
from flask_login import current_user, login_required
from .utils import teacher_required
import simplejson as json
teachers = Blueprint('teachers', __name__)

@teachers.route('/dashboard')
@login_required
@teacher_required
def dashboard():
    """Reinderizza alla schermata dashboard del professore"""

    return render_template('teachers/teacher_dashboard.html', courses=get_all_courses_from_teacher(current_user.id_user))


@teachers.route('/new_course', methods=['GET', 'POST'])
@login_required
@teacher_required
def newCourse():
    """Reinderizza al form di creazione di un nuovo corso"""

    form = NewCourse_Form()
    form.category.choices = [(category.id_category, category.c_name) for category in get_all_categories()]

    #Validazione del form e inserimento del corso nel database
    if form.validate_on_submit():
        insert_course(form)
        return redirect(url_for('teachers.dashboard'))
    return render_template('teachers/create_course.html', form=form)


@teachers.route('/edit_course/<int:id_course>', methods=['GET', 'POST'])
@login_required
@teacher_required
def edit_course(id_course):
    """Reinderizza alla schermata di modifica del corso selezionato"""

    data_string = request.form.get('a')
    data = {}

    if data_string:
        data = json.loads(data_string)
        update_course(id_course, data)

    categories_left = get_all_categories()
    category = get_course_category(id_course)
    categories_left.remove(category)

    return render_template('teachers/edit_course.html', course=get_course_by_id(id_course), categories=categories_left, this_category=category)


@teachers.route('<int:id_course>/new_lesson', methods=['GET', 'POST'])
@login_required
@teacher_required
def newLesson(id_course):
    """Reinderizza alla schermata di creazione di una nuova lezione"""

    if current_user.id_user is not get_course_owner(id_course):
        abort(404)
        
    new_lesson = NewLesson_Form()
    
    new_lesson.building.choices = [(building.id_building, building.b_name) for building in Building.query.all()]
 
    if request.method == 'POST':
        new_lesson.classroom.choices = [(classroom.id_classroom, classroom.c_name) for classroom in Classroom.query.filter(Classroom.id_building == request.form.get('building')).all()]
    else:
        new_lesson.classroom.choices = [(classroom.id_classroom, classroom.c_name) for classroom in Classroom.query.filter(Classroom.id_building == new_lesson.building.choices[0][0]).all()]

    #Validazione del form e controllo di una eventuale sovrapposizione con altre lezioni
    if new_lesson.validate_on_submit():
        if not check_lesson_availability(new_lesson):
            flash('L\' aula inserita è già prenotata', 'danger')
            return render_template('teachers/new_lesson.html', id_course=id_course, form=new_lesson)

        insert_lesson(new_lesson, id_course)
        # Lezione inserita
        return redirect(url_for('main.course_page', id=id_course))

    return render_template('teachers/new_lesson.html', id_course=id_course, form=new_lesson)


@teachers.route('/<int:id_course>/lessons', methods = ['GET','POST'])
@login_required
@teacher_required
def lessons(id_course):
    """Reinderizza alla schermata di visualizzazione delle lezioni del corso selezionato"""

    lessons = get_course_lessons(id_course)

    return render_template('teachers/lesson_list.html', course = get_course_by_id(id_course), lessons = lessons)



# UTILITY per Ajax

@teachers.route('/getClassrooms/<string:id_building>', methods=['GET', 'POST'])
@login_required
@teacher_required
def getClassrooms(id_building):
    """Seleziona tutte le aule di una sede (utilizzata nella richiesta AJAX)"""

    class_schema = ClassroomSchema(many=True)
    classrooms = get_classrooms_from_building(id_building)
    return jsonify(class_schema.dump(classrooms))

app/templates/course_page.html
{% extends 'layout.html' %}

{% block title %}{{ course.c_name }} - UniVE PCTO{% endblock %}

{% block content %}

<!-- Titolo -->
<div class="mb-3">
  <div class="fs-1 fw-bolder align-middle mb-2">
    {{ course.c_name }}
  </div>
</div>

<!-- Descrizione corso -->
<div class="mb-3">
  <div class="fs-4 fw-bold align-middle mb-2"><i class="fa-solid fa-map"></i> Descrizione</div>
  <span>{{ course.description }}</span>
</div>

<!-- Lezioni -->
<div class="mb-3">
  <span class="fs-4 fw-bold align-middle mb-2"><i class="fa-solid fa-chalkboard-user"></i> Lezioni</span>
  {% if session.role == 'teacher' %}
  <a name="" id="" class="btn btn-success ms-1" href="{{ url_for('teachers.newLesson', id_course = course.id_course) }}" role="button">
    <i class="fa-solid fa-calendar-plus"></i> Aggiungi
  </a>
  {% endif %}
  <div class="accordion mt-1" id="accordionLesson">
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingOne">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne"
                aria-expanded="true" aria-controls="collapseOne">
          Prossime lezioni
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne"
           data-bs-parent="#accordionLesson">
        <div class="card-body px-0 py-0">
          <ul class="list-group list-group-flush">
            {% if lessons is defined and lessons|length > 0 %}

            <table class="table mb-0">
              <thead>
                <tr>
                  <th scope="col">Data e orario</th>
                  <th scope="col">Modalità</th>
                  <th scope="col">Descrizione</th>
                  <th scope="col">Edificio</th>
                  <th scope="col">Aula</th>
                </tr>
              </thead>

              <tbody>
                {% for lesson in lessons %}

                <tr>
                  <th scope="row">
                    {{ lesson.Lesson.l_date | format_datetime('date') }}
                    -
                    {{ lesson.Lesson.l_date | format_datetime('time') }}
                  </th>
                  <td {{ 'class=text-primary' if lesson.Lesson.mode == 'Online' }}>
                    {{ lesson.Lesson.mode }}
                  </td>
                  <td>
                    <p>{{ lesson.Lesson.description}}</p>
                  </td>
                  <td>
                    {{ lesson.Building.b_name }}
                  </td>
                  <td>
                    {{ lesson.Classroom.c_name }}
                  </td>
                </tr>


                {% endfor %}
                {% else %}
                <li class="list-group-item">
                  Nessuna lezione in programma!
                </li>
                {% endif %}

              </tbody>
            </table>

        </div>
      </div>
    </div>
  </div>
</div>

<!-- Mappa -->
{% if map %}
<div class="mb-3">
    <div class="fs-4 fw-bold align-middle mb-2"><i class="fa-solid fa-location-dot"></i> Mappa</div>
      <div class="accordion" id="accordionMap">
        <div class="accordion-item">
          <h2 class="accordion-header" id="headingMap">
            <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseMap" aria-expanded="false" aria-controls="collapseMap">
              Espandi
            </button>
          </h2>
          <div id="collapseMap" class="accordion-collapse collapse" aria-labelledby="headingMap" data-bs-parent="#accordionMap">
            <div class="accordion-body">
              <!-- Visualizza mappa -->
              {{ map | safe }}
            </div>
          </div>
        </div>
        
      </div>

    </div>
{% endif %}

<!-- Partecipanti -->
{% if session.role == 'teacher' %}
<div class="mb-3">
  <div class="fs-4 fw-bold align-middle mb-2"><i class="fa-solid fa-user-group"></i> Partecipanti</div>
  <ul class="list-group">
    {% for student, reg in partecipants %}
    <li class="list-group-item ">
      <div class="d-flex justify-content-between">
        <div class="p-2">
          <img src="{{ student.email | gravatar }}" class="rounded-circle ms-1" height="22" alt="Avatar" loading="lazy" />
          <b>{{ student.first_name }} {{student.last_name}}</b>
          ({{ student.email }})
          {{ student.birth_date | format_datetime('date') }}
        </div>

        <div class="p-2">
          <b>Iscritto il: </b>
          {{ reg | format_datetime('date') }}
        </div>
      </div>
    </li>
    {% endfor %}
  </ul>
</div>
{% endif %}

{% endblock content %}

app/templates/courses.html
{% extends 'layout.html' %}
{% block content %}

<h1>Tutti i corsi</h1>

<table class="table table-hover">
    <thead>
        <tr>
            <th scope="col">Titolo</th>
            <th scope="col">Descrizione</th>
            <th scope="col">Creatore</th>
            <th scope="col">Data Creazione</th>
            <th scope="col">Numero iscrizioni massime</th>
            {% if type_user == 'student' %}
            <th scope="col">Disponibilità</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>

        {% for course in courses %}
        <tr>
            <th scope="row">{{course.c_name}}</th>
            <td>{{course.description}}</td>
            <td></td>
            <td>{{course.creation_date}}</td>
            <td>{{course.max_partecipants}}</td>

            {% if type_user == 'student' %}
            <td><button type="button" class="btn btn-success">Iscriviti</button></td>
            {% endif %}

        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock content %}

app/templates/index.html
{% extends 'layout.html' %}

{% block title %}UniVE PCTO{% endblock %}

{% block content %}
<div class="p-5 py-5 mb-4">
        <!-- <h1 class="display-5 fw-bold">PCTO</h1> -->
        <img src="{{url_for('static', filename='img/logo_unive.png')}}" class="img-fluid" alt="Responsive image"/>
        <ul class="list-group">
            {% for user in users %}
                <li class="list-group-item"><b>{{ user.first_name }} {{user.last_name}}</b>, {{user.email}}</li>
            {% endfor %}
        </ul>
    </div>
{% endblock content %}

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- JQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <!-- FontAwesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.1/css/all.css" integrity="sha384-/frq1SRXYH/bSyou/HUp/hib7RVN1TawQYja658FEOodR/FQBKVqT9Ol+Oz3Olq5" crossorigin="anonymous">
    <title>
      {% block title %}

      {% endblock %}
    </title>
    <link rel="shortcut icon" href="{{url_for('static', filename='img/favicon.ico')}}" type="image/x-icon">
  </head>
  <body>
    <header>
        <!-- NavBar di default -->
        <nav class="navbar navbar-expand-lg navbar-dark mb-3">
          <div class="container">
            <a class="navbar-brand h1 mb-0" href="{{ url_for('main.index') }}"><i class="fa-solid fa-graduation-cap"></i> PCTO UniVE</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

            {% if session['role'] == 'teacher' %}
              <!-- Navbar INSEGNANTI -->
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% for item in nav.teachers %}
                <li class="nav-item">
                  <a class="nav-link {{ 'active' if item.is_active else '' }}" aria-current="page" href="{{ item.url }}">{{ item.label}}</a>
                </li>
              {% endfor %}
              </ul>

              <ul class="navbar-nav">
                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <span class="badge rounded-pill text-dark bg-warning">Prof.</span> {{current_user.first_name}} {{ current_user.last_name }}
                    <img src="{{ current_user.email | gravatar }}" class="rounded-circle ms-1" height="22" alt="Avatar" loading="lazy" />
                  </a>
                  <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="navbarDarkDropdownMenuLink">
                    <li><a class="dropdown-item" href="{{ url_for('main.profile') }}">Profilo <i class="fa-solid fa-wrench"></i></a></li>
                    <li><hr class="dropdown-divider"></li>
                    <li><a class="dropdown-item text-danger" href="{{ url_for('main.logout') }}">Logout <i class="fa-solid fa-right-from-bracket"></i></a></li>
                  </ul>
                </li>
              </ul>
            {% elif session['role'] == 'student' %}
              <!-- Navbar STUDENTE -->
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% for item in nav.students %}
                  <li class="nav-item">
                    <a class="nav-link {{ 'active' if item.is_active else '' }}" aria-current="page" href="{{ item.url }}">{{ item.label }}</a>
                  </li>
                {% endfor %}
                </ul>
                <ul class="navbar-nav">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      {{current_user.first_name}} {{ current_user.last_name }}
                      <img src="{{ current_user.email | gravatar }}" class="rounded-circle ms-1" height="22" alt="Avatar" loading="lazy" /></a>
                    <ul class="dropdown-menu dropdown-menu-light" aria-labelledby="navbarDarkDropdownMenuLink">
                      <li><a class="dropdown-item" href="{{ url_for('main.profile') }}">Profilo <i class="fa-solid fa-wrench"></i></a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item text-danger" href="{{ url_for('main.logout') }}">Logout <i class="fa-solid fa-right-from-bracket"></i></a></li>
                    </ul>
                  </li>
                </ul>
              </div>
            {% else %}
                <!-- Navbar NON LOGGATO -->
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% for item in nav.not_logged %}
                  <li class="nav-item">
                    <a class="nav-link {{ 'active' if item.is_active else '' }}" aria-current="page" href="{{ item.url }}">{{ item.label }}</a>
                  </li>
                {% endfor %}
                </ul>
            {% endif %}
            </div>
          </div>
        </nav>
    </header>

    <main role="main" class="container">
        {% with messages = get_flashed_messages(with_categories = true) %}
            {% if messages %}
                    {% for category, message in messages %}
                    <div class="alert alert-{{category}} alert-dismissible fade show">
                        {{message}}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
            {% endif %}
        {% endwith %}

        <div id="alertPlaceholder"></div>

        <div class="card outer">
          {% block cardHeader %}

          {% endblock %}
          <div class="container">
            <div class="card-body">
              {% block content %}

              {% endblock %}
            </div>
          </div>
        </div>

    </main>

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
  </body>
</html>

<style>
  nav.navbar{
    background-color: #ac0033;
  }

  body {
      background-color: #eee
  }

  .card.outer{
      border: none;
      border-radius: 10px
  }

  .c-details span {
      font-weight: 300;
      font-size: 13px
  }

  .progress {
      height: 10px;
      border-radius: 10px
  }

  .progress div {
      background-color:red
  }

  html{
      font-size: 15px;
      font-weight: 600
  }

  .text2 {
      color: #a5aec0
  }
</style>

app/templates/login.html
{% extends 'layout.html' %}

{% block title %}Login - UniVE PCTO{% endblock %}

{% block cardHeader %}

<div class="card-header">
        <div class="card-body py-1">
            <h3 class="card-title">Login</h3>
        </div>
</div>

{% endblock %}

{% block content %}
    <form action="" method="post" novalidate>
        {{ form.hidden_tag() }}

        <div class="mb-3">
            {{ form.email.label(class="form-label") }}
            {% if form.email.errors %}
                    {{form.email(class="form-control is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
            {% else %}
                {{ form.email(class="form-control") }}
            {% endif %}
        </div>

        <div class="mb-3">
            {{ form.password.label(class="form-label") }}
            {% if form.password.errors %}
                    {{form.password(class="form-control is-invalid")}}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{error}}</span>
                        {% endfor %}
                    </div>
            {% else %}
                {{ form.password(class="form-control") }}
            {% endif %}
        </div>

        <div class="mb-3">
            {{ form.submit(class="btn btn-primary") }}
        </div>
    </form>
    <small>Non sei ancora registrato? <a href="{{ url_for('main.register') }}">Registrati</a></small><br>
{% endblock content %}

app/templates/profile.html
{% extends 'layout.html' %}

{% block title %}Profilo - UniVE PCTO{% endblock %}

{% block content %}

    <h1>Profilo di {{current_user.first_name}}</h1>

    <h4>Informazioni</h4>

    <div class="d-flex align-items-stretch bg-light">
        <div>
            <img src="{{ current_user.email | gravatar }}" class="mx-auto d-block p-2" height="135" alt="Avatar" loading="lazy" />
        </div>
        <div class="d-flex flex-column mb-3">
            <div class="p-1"><span class="badge bg-warning text-dark">Nome:</span> {{current_user.first_name}}</div>
            <div class="p-1"><span class="badge bg-warning text-dark">Cognome:</span> {{current_user.last_name}}</div>
            <div class="p-1"><span class="badge bg-warning text-dark">Data di nascita:</span> {{current_user.birth_date}} </div> 
            <div class="p-1"><span class="badge bg-warning text-dark">Email:</span> {{current_user.email}}</div>
        </div>
    </div>

{% endblock content %}